# Generated by Django 5.0.4 on 2024-04-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipos',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
