# Generated by Django 5.0.4 on 2024-04-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_equipos_estado_equiposcampeonato_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campeonato',
            name='tipo',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
