# Generated by Django 5.0.4 on 2024-04-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_campeonato_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
