# Generated by Django 5.0.4 on 2024-04-23 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_eventos_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipos',
            name='escudo',
            field=models.ImageField(default='escudos_imagenes/general.png', upload_to='escudos_imagenes/'),
        ),
    ]
