# Generated by Django 5.0.4 on 2024-04-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_equipos_escudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='campeonato',
            name='cupos_disponibles',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='campeonato',
            name='tipo',
            field=models.IntegerField(null=True),
        ),
    ]
