# Generated by Django 5.0.4 on 2024-04-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_campeonato_cupos_disponibles_alter_campeonato_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='campeonato',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
